name: ginkgo_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  base: 
    path: ./base
  flutter_svg: ^0.17.4
  auto_size_text: ^2.1.0
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  toast: ^0.1.5
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/