name: base
description: Base for Ginkgo mobile.
version: 0.0.1
author: Hieren Lee

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^4.0.0
  dio: ^3.0.9
  flutter_secure_storage: ^3.3.1+1
  connectivity: ^0.4.8+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
