name: New Release

on:
  push:
    branches:
      - new-ci

jobs:
  build:
    name: Build and Ios
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '1.17.3'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
